services:
  db:
    image: postgres:16
    container_name: eval
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eval_db
    ports:
      - "5445:5432"

volumes:
  postgres_data:
